//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsBilgisi
    {
        public int IsId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public string FirmaAdi { get; set; }
        public string Gorev { get; set; }
        public Nullable<int> CalismaYili { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
