//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelBilgiFormu2Entities1 : DbContext
    {
        public PersonelBilgiFormu2Entities1()
            : base("name=PersonelBilgiFormu2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Belgeler> Belgeler { get; set; }
        public virtual DbSet<IsBilgisi> IsBilgisi { get; set; }
        public virtual DbSet<OkulBilgisi> OkulBilgisi { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
    }
}
